#!/bin/sh

# to debug tests, change "mvn test" to "mvn -DforkMode=never test" and uncomment this line
#export MAVEN_OPTS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"

# run tests then if there were any test failures, print the text reports
mvn test || cat `grep --files-with-matches FAILURE */target/surefire-reports/*.txt`