// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GraphData.proto

public final class GraphData {
  private GraphData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ObjectGraph extends
      com.google.protobuf.GeneratedMessage {
    // Use ObjectGraph.newBuilder() to construct.
    private ObjectGraph() {
      initFields();
    }
    private ObjectGraph(boolean noInit) {}
    
    private static final ObjectGraph defaultInstance;
    public static ObjectGraph getDefaultInstance() {
      return defaultInstance;
    }
    
    public ObjectGraph getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GraphData.internal_static_ObjectGraph_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GraphData.internal_static_ObjectGraph_fieldAccessorTable;
    }
    
    // required string domainId = 1;
    public static final int DOMAINID_FIELD_NUMBER = 1;
    private boolean hasDomainId;
    private java.lang.String domainId_ = "";
    public boolean hasDomainId() { return hasDomainId; }
    public java.lang.String getDomainId() { return domainId_; }
    
    // required string dataVersionScheme = 2;
    public static final int DATAVERSIONSCHEME_FIELD_NUMBER = 2;
    private boolean hasDataVersionScheme;
    private java.lang.String dataVersionScheme_ = "";
    public boolean hasDataVersionScheme() { return hasDataVersionScheme; }
    public java.lang.String getDataVersionScheme() { return dataVersionScheme_; }
    
    // required int32 dataVersion = 3;
    public static final int DATAVERSION_FIELD_NUMBER = 3;
    private boolean hasDataVersion;
    private int dataVersion_ = 0;
    public boolean hasDataVersion() { return hasDataVersion; }
    public int getDataVersion() { return dataVersion_; }
    
    // repeated .EntityValue entityValues = 4;
    public static final int ENTITYVALUES_FIELD_NUMBER = 4;
    private java.util.List<GraphData.EntityValue> entityValues_ =
      java.util.Collections.emptyList();
    public java.util.List<GraphData.EntityValue> getEntityValuesList() {
      return entityValues_;
    }
    public int getEntityValuesCount() { return entityValues_.size(); }
    public GraphData.EntityValue getEntityValues(int index) {
      return entityValues_.get(index);
    }
    
    // repeated .EntityUpdate entityUpdates = 5;
    public static final int ENTITYUPDATES_FIELD_NUMBER = 5;
    private java.util.List<GraphData.EntityUpdate> entityUpdates_ =
      java.util.Collections.emptyList();
    public java.util.List<GraphData.EntityUpdate> getEntityUpdatesList() {
      return entityUpdates_;
    }
    public int getEntityUpdatesCount() { return entityUpdates_.size(); }
    public GraphData.EntityUpdate getEntityUpdates(int index) {
      return entityUpdates_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasDomainId) return false;
      if (!hasDataVersionScheme) return false;
      if (!hasDataVersion) return false;
      for (GraphData.EntityValue element : getEntityValuesList()) {
        if (!element.isInitialized()) return false;
      }
      for (GraphData.EntityUpdate element : getEntityUpdatesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasDomainId()) {
        output.writeString(1, getDomainId());
      }
      if (hasDataVersionScheme()) {
        output.writeString(2, getDataVersionScheme());
      }
      if (hasDataVersion()) {
        output.writeInt32(3, getDataVersion());
      }
      for (GraphData.EntityValue element : getEntityValuesList()) {
        output.writeMessage(4, element);
      }
      for (GraphData.EntityUpdate element : getEntityUpdatesList()) {
        output.writeMessage(5, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasDomainId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getDomainId());
      }
      if (hasDataVersionScheme()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDataVersionScheme());
      }
      if (hasDataVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getDataVersion());
      }
      for (GraphData.EntityValue element : getEntityValuesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      for (GraphData.EntityUpdate element : getEntityUpdatesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static GraphData.ObjectGraph parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.ObjectGraph parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.ObjectGraph parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.ObjectGraph parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.ObjectGraph parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.ObjectGraph parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.ObjectGraph parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.ObjectGraph parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.ObjectGraph parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.ObjectGraph parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GraphData.ObjectGraph prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private GraphData.ObjectGraph result;
      
      // Construct using GraphData.ObjectGraph.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new GraphData.ObjectGraph();
        return builder;
      }
      
      protected GraphData.ObjectGraph internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new GraphData.ObjectGraph();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GraphData.ObjectGraph.getDescriptor();
      }
      
      public GraphData.ObjectGraph getDefaultInstanceForType() {
        return GraphData.ObjectGraph.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public GraphData.ObjectGraph build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private GraphData.ObjectGraph buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public GraphData.ObjectGraph buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.entityValues_ != java.util.Collections.EMPTY_LIST) {
          result.entityValues_ =
            java.util.Collections.unmodifiableList(result.entityValues_);
        }
        if (result.entityUpdates_ != java.util.Collections.EMPTY_LIST) {
          result.entityUpdates_ =
            java.util.Collections.unmodifiableList(result.entityUpdates_);
        }
        GraphData.ObjectGraph returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GraphData.ObjectGraph) {
          return mergeFrom((GraphData.ObjectGraph)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(GraphData.ObjectGraph other) {
        if (other == GraphData.ObjectGraph.getDefaultInstance()) return this;
        if (other.hasDomainId()) {
          setDomainId(other.getDomainId());
        }
        if (other.hasDataVersionScheme()) {
          setDataVersionScheme(other.getDataVersionScheme());
        }
        if (other.hasDataVersion()) {
          setDataVersion(other.getDataVersion());
        }
        if (!other.entityValues_.isEmpty()) {
          if (result.entityValues_.isEmpty()) {
            result.entityValues_ = new java.util.ArrayList<GraphData.EntityValue>();
          }
          result.entityValues_.addAll(other.entityValues_);
        }
        if (!other.entityUpdates_.isEmpty()) {
          if (result.entityUpdates_.isEmpty()) {
            result.entityUpdates_ = new java.util.ArrayList<GraphData.EntityUpdate>();
          }
          result.entityUpdates_.addAll(other.entityUpdates_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setDomainId(input.readString());
              break;
            }
            case 18: {
              setDataVersionScheme(input.readString());
              break;
            }
            case 24: {
              setDataVersion(input.readInt32());
              break;
            }
            case 34: {
              GraphData.EntityValue.Builder subBuilder = GraphData.EntityValue.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEntityValues(subBuilder.buildPartial());
              break;
            }
            case 42: {
              GraphData.EntityUpdate.Builder subBuilder = GraphData.EntityUpdate.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEntityUpdates(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string domainId = 1;
      public boolean hasDomainId() {
        return result.hasDomainId();
      }
      public java.lang.String getDomainId() {
        return result.getDomainId();
      }
      public Builder setDomainId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDomainId = true;
        result.domainId_ = value;
        return this;
      }
      public Builder clearDomainId() {
        result.hasDomainId = false;
        result.domainId_ = getDefaultInstance().getDomainId();
        return this;
      }
      
      // required string dataVersionScheme = 2;
      public boolean hasDataVersionScheme() {
        return result.hasDataVersionScheme();
      }
      public java.lang.String getDataVersionScheme() {
        return result.getDataVersionScheme();
      }
      public Builder setDataVersionScheme(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDataVersionScheme = true;
        result.dataVersionScheme_ = value;
        return this;
      }
      public Builder clearDataVersionScheme() {
        result.hasDataVersionScheme = false;
        result.dataVersionScheme_ = getDefaultInstance().getDataVersionScheme();
        return this;
      }
      
      // required int32 dataVersion = 3;
      public boolean hasDataVersion() {
        return result.hasDataVersion();
      }
      public int getDataVersion() {
        return result.getDataVersion();
      }
      public Builder setDataVersion(int value) {
        result.hasDataVersion = true;
        result.dataVersion_ = value;
        return this;
      }
      public Builder clearDataVersion() {
        result.hasDataVersion = false;
        result.dataVersion_ = 0;
        return this;
      }
      
      // repeated .EntityValue entityValues = 4;
      public java.util.List<GraphData.EntityValue> getEntityValuesList() {
        return java.util.Collections.unmodifiableList(result.entityValues_);
      }
      public int getEntityValuesCount() {
        return result.getEntityValuesCount();
      }
      public GraphData.EntityValue getEntityValues(int index) {
        return result.getEntityValues(index);
      }
      public Builder setEntityValues(int index, GraphData.EntityValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.entityValues_.set(index, value);
        return this;
      }
      public Builder setEntityValues(int index, GraphData.EntityValue.Builder builderForValue) {
        result.entityValues_.set(index, builderForValue.build());
        return this;
      }
      public Builder addEntityValues(GraphData.EntityValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.entityValues_.isEmpty()) {
          result.entityValues_ = new java.util.ArrayList<GraphData.EntityValue>();
        }
        result.entityValues_.add(value);
        return this;
      }
      public Builder addEntityValues(GraphData.EntityValue.Builder builderForValue) {
        if (result.entityValues_.isEmpty()) {
          result.entityValues_ = new java.util.ArrayList<GraphData.EntityValue>();
        }
        result.entityValues_.add(builderForValue.build());
        return this;
      }
      public Builder addAllEntityValues(
          java.lang.Iterable<? extends GraphData.EntityValue> values) {
        if (result.entityValues_.isEmpty()) {
          result.entityValues_ = new java.util.ArrayList<GraphData.EntityValue>();
        }
        super.addAll(values, result.entityValues_);
        return this;
      }
      public Builder clearEntityValues() {
        result.entityValues_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .EntityUpdate entityUpdates = 5;
      public java.util.List<GraphData.EntityUpdate> getEntityUpdatesList() {
        return java.util.Collections.unmodifiableList(result.entityUpdates_);
      }
      public int getEntityUpdatesCount() {
        return result.getEntityUpdatesCount();
      }
      public GraphData.EntityUpdate getEntityUpdates(int index) {
        return result.getEntityUpdates(index);
      }
      public Builder setEntityUpdates(int index, GraphData.EntityUpdate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.entityUpdates_.set(index, value);
        return this;
      }
      public Builder setEntityUpdates(int index, GraphData.EntityUpdate.Builder builderForValue) {
        result.entityUpdates_.set(index, builderForValue.build());
        return this;
      }
      public Builder addEntityUpdates(GraphData.EntityUpdate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.entityUpdates_.isEmpty()) {
          result.entityUpdates_ = new java.util.ArrayList<GraphData.EntityUpdate>();
        }
        result.entityUpdates_.add(value);
        return this;
      }
      public Builder addEntityUpdates(GraphData.EntityUpdate.Builder builderForValue) {
        if (result.entityUpdates_.isEmpty()) {
          result.entityUpdates_ = new java.util.ArrayList<GraphData.EntityUpdate>();
        }
        result.entityUpdates_.add(builderForValue.build());
        return this;
      }
      public Builder addAllEntityUpdates(
          java.lang.Iterable<? extends GraphData.EntityUpdate> values) {
        if (result.entityUpdates_.isEmpty()) {
          result.entityUpdates_ = new java.util.ArrayList<GraphData.EntityUpdate>();
        }
        super.addAll(values, result.entityUpdates_);
        return this;
      }
      public Builder clearEntityUpdates() {
        result.entityUpdates_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ObjectGraph)
    }
    
    static {
      defaultInstance = new ObjectGraph(true);
      GraphData.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ObjectGraph)
  }
  
  public static final class EntityValue extends
      com.google.protobuf.GeneratedMessage {
    // Use EntityValue.newBuilder() to construct.
    private EntityValue() {
      initFields();
    }
    private EntityValue(boolean noInit) {}
    
    private static final EntityValue defaultInstance;
    public static EntityValue getDefaultInstance() {
      return defaultInstance;
    }
    
    public EntityValue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GraphData.internal_static_EntityValue_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GraphData.internal_static_EntityValue_fieldAccessorTable;
    }
    
    // required int32 classId = 1;
    public static final int CLASSID_FIELD_NUMBER = 1;
    private boolean hasClassId;
    private int classId_ = 0;
    public boolean hasClassId() { return hasClassId; }
    public int getClassId() { return classId_; }
    
    // required int64 entityId = 2;
    public static final int ENTITYID_FIELD_NUMBER = 2;
    private boolean hasEntityId;
    private long entityId_ = 0L;
    public boolean hasEntityId() { return hasEntityId; }
    public long getEntityId() { return entityId_; }
    
    // repeated .PropertyValue propertyValues = 3;
    public static final int PROPERTYVALUES_FIELD_NUMBER = 3;
    private java.util.List<GraphData.PropertyValue> propertyValues_ =
      java.util.Collections.emptyList();
    public java.util.List<GraphData.PropertyValue> getPropertyValuesList() {
      return propertyValues_;
    }
    public int getPropertyValuesCount() { return propertyValues_.size(); }
    public GraphData.PropertyValue getPropertyValues(int index) {
      return propertyValues_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasClassId) return false;
      if (!hasEntityId) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasClassId()) {
        output.writeInt32(1, getClassId());
      }
      if (hasEntityId()) {
        output.writeInt64(2, getEntityId());
      }
      for (GraphData.PropertyValue element : getPropertyValuesList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasClassId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getClassId());
      }
      if (hasEntityId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getEntityId());
      }
      for (GraphData.PropertyValue element : getPropertyValuesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static GraphData.EntityValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.EntityValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.EntityValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.EntityValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.EntityValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.EntityValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.EntityValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.EntityValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.EntityValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.EntityValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GraphData.EntityValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private GraphData.EntityValue result;
      
      // Construct using GraphData.EntityValue.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new GraphData.EntityValue();
        return builder;
      }
      
      protected GraphData.EntityValue internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new GraphData.EntityValue();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GraphData.EntityValue.getDescriptor();
      }
      
      public GraphData.EntityValue getDefaultInstanceForType() {
        return GraphData.EntityValue.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public GraphData.EntityValue build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private GraphData.EntityValue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public GraphData.EntityValue buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.propertyValues_ != java.util.Collections.EMPTY_LIST) {
          result.propertyValues_ =
            java.util.Collections.unmodifiableList(result.propertyValues_);
        }
        GraphData.EntityValue returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GraphData.EntityValue) {
          return mergeFrom((GraphData.EntityValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(GraphData.EntityValue other) {
        if (other == GraphData.EntityValue.getDefaultInstance()) return this;
        if (other.hasClassId()) {
          setClassId(other.getClassId());
        }
        if (other.hasEntityId()) {
          setEntityId(other.getEntityId());
        }
        if (!other.propertyValues_.isEmpty()) {
          if (result.propertyValues_.isEmpty()) {
            result.propertyValues_ = new java.util.ArrayList<GraphData.PropertyValue>();
          }
          result.propertyValues_.addAll(other.propertyValues_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setClassId(input.readInt32());
              break;
            }
            case 16: {
              setEntityId(input.readInt64());
              break;
            }
            case 26: {
              GraphData.PropertyValue.Builder subBuilder = GraphData.PropertyValue.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPropertyValues(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 classId = 1;
      public boolean hasClassId() {
        return result.hasClassId();
      }
      public int getClassId() {
        return result.getClassId();
      }
      public Builder setClassId(int value) {
        result.hasClassId = true;
        result.classId_ = value;
        return this;
      }
      public Builder clearClassId() {
        result.hasClassId = false;
        result.classId_ = 0;
        return this;
      }
      
      // required int64 entityId = 2;
      public boolean hasEntityId() {
        return result.hasEntityId();
      }
      public long getEntityId() {
        return result.getEntityId();
      }
      public Builder setEntityId(long value) {
        result.hasEntityId = true;
        result.entityId_ = value;
        return this;
      }
      public Builder clearEntityId() {
        result.hasEntityId = false;
        result.entityId_ = 0L;
        return this;
      }
      
      // repeated .PropertyValue propertyValues = 3;
      public java.util.List<GraphData.PropertyValue> getPropertyValuesList() {
        return java.util.Collections.unmodifiableList(result.propertyValues_);
      }
      public int getPropertyValuesCount() {
        return result.getPropertyValuesCount();
      }
      public GraphData.PropertyValue getPropertyValues(int index) {
        return result.getPropertyValues(index);
      }
      public Builder setPropertyValues(int index, GraphData.PropertyValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.propertyValues_.set(index, value);
        return this;
      }
      public Builder setPropertyValues(int index, GraphData.PropertyValue.Builder builderForValue) {
        result.propertyValues_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPropertyValues(GraphData.PropertyValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.propertyValues_.isEmpty()) {
          result.propertyValues_ = new java.util.ArrayList<GraphData.PropertyValue>();
        }
        result.propertyValues_.add(value);
        return this;
      }
      public Builder addPropertyValues(GraphData.PropertyValue.Builder builderForValue) {
        if (result.propertyValues_.isEmpty()) {
          result.propertyValues_ = new java.util.ArrayList<GraphData.PropertyValue>();
        }
        result.propertyValues_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPropertyValues(
          java.lang.Iterable<? extends GraphData.PropertyValue> values) {
        if (result.propertyValues_.isEmpty()) {
          result.propertyValues_ = new java.util.ArrayList<GraphData.PropertyValue>();
        }
        super.addAll(values, result.propertyValues_);
        return this;
      }
      public Builder clearPropertyValues() {
        result.propertyValues_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:EntityValue)
    }
    
    static {
      defaultInstance = new EntityValue(true);
      GraphData.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:EntityValue)
  }
  
  public static final class EntityUpdate extends
      com.google.protobuf.GeneratedMessage {
    // Use EntityUpdate.newBuilder() to construct.
    private EntityUpdate() {
      initFields();
    }
    private EntityUpdate(boolean noInit) {}
    
    private static final EntityUpdate defaultInstance;
    public static EntityUpdate getDefaultInstance() {
      return defaultInstance;
    }
    
    public EntityUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GraphData.internal_static_EntityUpdate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GraphData.internal_static_EntityUpdate_fieldAccessorTable;
    }
    
    // required int32 classId = 1;
    public static final int CLASSID_FIELD_NUMBER = 1;
    private boolean hasClassId;
    private int classId_ = 0;
    public boolean hasClassId() { return hasClassId; }
    public int getClassId() { return classId_; }
    
    // required int64 entityId = 2;
    public static final int ENTITYID_FIELD_NUMBER = 2;
    private boolean hasEntityId;
    private long entityId_ = 0L;
    public boolean hasEntityId() { return hasEntityId; }
    public long getEntityId() { return entityId_; }
    
    // repeated .PropertyUpdate propertyUpdates = 3;
    public static final int PROPERTYUPDATES_FIELD_NUMBER = 3;
    private java.util.List<GraphData.PropertyUpdate> propertyUpdates_ =
      java.util.Collections.emptyList();
    public java.util.List<GraphData.PropertyUpdate> getPropertyUpdatesList() {
      return propertyUpdates_;
    }
    public int getPropertyUpdatesCount() { return propertyUpdates_.size(); }
    public GraphData.PropertyUpdate getPropertyUpdates(int index) {
      return propertyUpdates_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasClassId) return false;
      if (!hasEntityId) return false;
      for (GraphData.PropertyUpdate element : getPropertyUpdatesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasClassId()) {
        output.writeInt32(1, getClassId());
      }
      if (hasEntityId()) {
        output.writeInt64(2, getEntityId());
      }
      for (GraphData.PropertyUpdate element : getPropertyUpdatesList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasClassId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getClassId());
      }
      if (hasEntityId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getEntityId());
      }
      for (GraphData.PropertyUpdate element : getPropertyUpdatesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static GraphData.EntityUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.EntityUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.EntityUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.EntityUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.EntityUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.EntityUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.EntityUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.EntityUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.EntityUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.EntityUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GraphData.EntityUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private GraphData.EntityUpdate result;
      
      // Construct using GraphData.EntityUpdate.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new GraphData.EntityUpdate();
        return builder;
      }
      
      protected GraphData.EntityUpdate internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new GraphData.EntityUpdate();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GraphData.EntityUpdate.getDescriptor();
      }
      
      public GraphData.EntityUpdate getDefaultInstanceForType() {
        return GraphData.EntityUpdate.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public GraphData.EntityUpdate build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private GraphData.EntityUpdate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public GraphData.EntityUpdate buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.propertyUpdates_ != java.util.Collections.EMPTY_LIST) {
          result.propertyUpdates_ =
            java.util.Collections.unmodifiableList(result.propertyUpdates_);
        }
        GraphData.EntityUpdate returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GraphData.EntityUpdate) {
          return mergeFrom((GraphData.EntityUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(GraphData.EntityUpdate other) {
        if (other == GraphData.EntityUpdate.getDefaultInstance()) return this;
        if (other.hasClassId()) {
          setClassId(other.getClassId());
        }
        if (other.hasEntityId()) {
          setEntityId(other.getEntityId());
        }
        if (!other.propertyUpdates_.isEmpty()) {
          if (result.propertyUpdates_.isEmpty()) {
            result.propertyUpdates_ = new java.util.ArrayList<GraphData.PropertyUpdate>();
          }
          result.propertyUpdates_.addAll(other.propertyUpdates_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setClassId(input.readInt32());
              break;
            }
            case 16: {
              setEntityId(input.readInt64());
              break;
            }
            case 26: {
              GraphData.PropertyUpdate.Builder subBuilder = GraphData.PropertyUpdate.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPropertyUpdates(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 classId = 1;
      public boolean hasClassId() {
        return result.hasClassId();
      }
      public int getClassId() {
        return result.getClassId();
      }
      public Builder setClassId(int value) {
        result.hasClassId = true;
        result.classId_ = value;
        return this;
      }
      public Builder clearClassId() {
        result.hasClassId = false;
        result.classId_ = 0;
        return this;
      }
      
      // required int64 entityId = 2;
      public boolean hasEntityId() {
        return result.hasEntityId();
      }
      public long getEntityId() {
        return result.getEntityId();
      }
      public Builder setEntityId(long value) {
        result.hasEntityId = true;
        result.entityId_ = value;
        return this;
      }
      public Builder clearEntityId() {
        result.hasEntityId = false;
        result.entityId_ = 0L;
        return this;
      }
      
      // repeated .PropertyUpdate propertyUpdates = 3;
      public java.util.List<GraphData.PropertyUpdate> getPropertyUpdatesList() {
        return java.util.Collections.unmodifiableList(result.propertyUpdates_);
      }
      public int getPropertyUpdatesCount() {
        return result.getPropertyUpdatesCount();
      }
      public GraphData.PropertyUpdate getPropertyUpdates(int index) {
        return result.getPropertyUpdates(index);
      }
      public Builder setPropertyUpdates(int index, GraphData.PropertyUpdate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.propertyUpdates_.set(index, value);
        return this;
      }
      public Builder setPropertyUpdates(int index, GraphData.PropertyUpdate.Builder builderForValue) {
        result.propertyUpdates_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPropertyUpdates(GraphData.PropertyUpdate value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.propertyUpdates_.isEmpty()) {
          result.propertyUpdates_ = new java.util.ArrayList<GraphData.PropertyUpdate>();
        }
        result.propertyUpdates_.add(value);
        return this;
      }
      public Builder addPropertyUpdates(GraphData.PropertyUpdate.Builder builderForValue) {
        if (result.propertyUpdates_.isEmpty()) {
          result.propertyUpdates_ = new java.util.ArrayList<GraphData.PropertyUpdate>();
        }
        result.propertyUpdates_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPropertyUpdates(
          java.lang.Iterable<? extends GraphData.PropertyUpdate> values) {
        if (result.propertyUpdates_.isEmpty()) {
          result.propertyUpdates_ = new java.util.ArrayList<GraphData.PropertyUpdate>();
        }
        super.addAll(values, result.propertyUpdates_);
        return this;
      }
      public Builder clearPropertyUpdates() {
        result.propertyUpdates_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:EntityUpdate)
    }
    
    static {
      defaultInstance = new EntityUpdate(true);
      GraphData.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:EntityUpdate)
  }
  
  public static final class PropertyUpdate extends
      com.google.protobuf.GeneratedMessage {
    // Use PropertyUpdate.newBuilder() to construct.
    private PropertyUpdate() {
      initFields();
    }
    private PropertyUpdate(boolean noInit) {}
    
    private static final PropertyUpdate defaultInstance;
    public static PropertyUpdate getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropertyUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GraphData.internal_static_PropertyUpdate_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GraphData.internal_static_PropertyUpdate_fieldAccessorTable;
    }
    
    // required int32 propertyCode = 1;
    public static final int PROPERTYCODE_FIELD_NUMBER = 1;
    private boolean hasPropertyCode;
    private int propertyCode_ = 0;
    public boolean hasPropertyCode() { return hasPropertyCode; }
    public int getPropertyCode() { return propertyCode_; }
    
    // required .PropertyValue newValue = 2;
    public static final int NEWVALUE_FIELD_NUMBER = 2;
    private boolean hasNewValue;
    private GraphData.PropertyValue newValue_;
    public boolean hasNewValue() { return hasNewValue; }
    public GraphData.PropertyValue getNewValue() { return newValue_; }
    
    private void initFields() {
      newValue_ = GraphData.PropertyValue.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasPropertyCode) return false;
      if (!hasNewValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPropertyCode()) {
        output.writeInt32(1, getPropertyCode());
      }
      if (hasNewValue()) {
        output.writeMessage(2, getNewValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPropertyCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getPropertyCode());
      }
      if (hasNewValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getNewValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static GraphData.PropertyUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.PropertyUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.PropertyUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.PropertyUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.PropertyUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.PropertyUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.PropertyUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.PropertyUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.PropertyUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.PropertyUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GraphData.PropertyUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private GraphData.PropertyUpdate result;
      
      // Construct using GraphData.PropertyUpdate.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new GraphData.PropertyUpdate();
        return builder;
      }
      
      protected GraphData.PropertyUpdate internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new GraphData.PropertyUpdate();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GraphData.PropertyUpdate.getDescriptor();
      }
      
      public GraphData.PropertyUpdate getDefaultInstanceForType() {
        return GraphData.PropertyUpdate.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public GraphData.PropertyUpdate build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private GraphData.PropertyUpdate buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public GraphData.PropertyUpdate buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        GraphData.PropertyUpdate returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GraphData.PropertyUpdate) {
          return mergeFrom((GraphData.PropertyUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(GraphData.PropertyUpdate other) {
        if (other == GraphData.PropertyUpdate.getDefaultInstance()) return this;
        if (other.hasPropertyCode()) {
          setPropertyCode(other.getPropertyCode());
        }
        if (other.hasNewValue()) {
          mergeNewValue(other.getNewValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setPropertyCode(input.readInt32());
              break;
            }
            case 18: {
              GraphData.PropertyValue.Builder subBuilder = GraphData.PropertyValue.newBuilder();
              if (hasNewValue()) {
                subBuilder.mergeFrom(getNewValue());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setNewValue(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required int32 propertyCode = 1;
      public boolean hasPropertyCode() {
        return result.hasPropertyCode();
      }
      public int getPropertyCode() {
        return result.getPropertyCode();
      }
      public Builder setPropertyCode(int value) {
        result.hasPropertyCode = true;
        result.propertyCode_ = value;
        return this;
      }
      public Builder clearPropertyCode() {
        result.hasPropertyCode = false;
        result.propertyCode_ = 0;
        return this;
      }
      
      // required .PropertyValue newValue = 2;
      public boolean hasNewValue() {
        return result.hasNewValue();
      }
      public GraphData.PropertyValue getNewValue() {
        return result.getNewValue();
      }
      public Builder setNewValue(GraphData.PropertyValue value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasNewValue = true;
        result.newValue_ = value;
        return this;
      }
      public Builder setNewValue(GraphData.PropertyValue.Builder builderForValue) {
        result.hasNewValue = true;
        result.newValue_ = builderForValue.build();
        return this;
      }
      public Builder mergeNewValue(GraphData.PropertyValue value) {
        if (result.hasNewValue() &&
            result.newValue_ != GraphData.PropertyValue.getDefaultInstance()) {
          result.newValue_ =
            GraphData.PropertyValue.newBuilder(result.newValue_).mergeFrom(value).buildPartial();
        } else {
          result.newValue_ = value;
        }
        result.hasNewValue = true;
        return this;
      }
      public Builder clearNewValue() {
        result.hasNewValue = false;
        result.newValue_ = GraphData.PropertyValue.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PropertyUpdate)
    }
    
    static {
      defaultInstance = new PropertyUpdate(true);
      GraphData.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PropertyUpdate)
  }
  
  public static final class PropertyValue extends
      com.google.protobuf.GeneratedMessage {
    // Use PropertyValue.newBuilder() to construct.
    private PropertyValue() {
      initFields();
    }
    private PropertyValue(boolean noInit) {}
    
    private static final PropertyValue defaultInstance;
    public static PropertyValue getDefaultInstance() {
      return defaultInstance;
    }
    
    public PropertyValue getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GraphData.internal_static_PropertyValue_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GraphData.internal_static_PropertyValue_fieldAccessorTable;
    }
    
    // optional bytes data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private boolean hasData;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasData() { return hasData; }
    public com.google.protobuf.ByteString getData() { return data_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasData()) {
        output.writeBytes(1, getData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static GraphData.PropertyValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.PropertyValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.PropertyValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static GraphData.PropertyValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.PropertyValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.PropertyValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static GraphData.PropertyValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.PropertyValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static GraphData.PropertyValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static GraphData.PropertyValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GraphData.PropertyValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private GraphData.PropertyValue result;
      
      // Construct using GraphData.PropertyValue.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new GraphData.PropertyValue();
        return builder;
      }
      
      protected GraphData.PropertyValue internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new GraphData.PropertyValue();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GraphData.PropertyValue.getDescriptor();
      }
      
      public GraphData.PropertyValue getDefaultInstanceForType() {
        return GraphData.PropertyValue.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public GraphData.PropertyValue build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private GraphData.PropertyValue buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public GraphData.PropertyValue buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        GraphData.PropertyValue returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GraphData.PropertyValue) {
          return mergeFrom((GraphData.PropertyValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(GraphData.PropertyValue other) {
        if (other == GraphData.PropertyValue.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setData(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional bytes data = 1;
      public boolean hasData() {
        return result.hasData();
      }
      public com.google.protobuf.ByteString getData() {
        return result.getData();
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasData = true;
        result.data_ = value;
        return this;
      }
      public Builder clearData() {
        result.hasData = false;
        result.data_ = getDefaultInstance().getData();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:PropertyValue)
    }
    
    static {
      defaultInstance = new PropertyValue(true);
      GraphData.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:PropertyValue)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ObjectGraph_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ObjectGraph_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EntityValue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EntityUpdate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PropertyUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PropertyUpdate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PropertyValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PropertyValue_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017GraphData.proto\"\231\001\n\013ObjectGraph\022\020\n\010dom" +
      "ainId\030\001 \002(\t\022\031\n\021dataVersionScheme\030\002 \002(\t\022\023" +
      "\n\013dataVersion\030\003 \002(\005\022\"\n\014entityValues\030\004 \003(" +
      "\0132\014.EntityValue\022$\n\rentityUpdates\030\005 \003(\0132\r" +
      ".EntityUpdate\"X\n\013EntityValue\022\017\n\007classId\030" +
      "\001 \002(\005\022\020\n\010entityId\030\002 \002(\003\022&\n\016propertyValue" +
      "s\030\003 \003(\0132\016.PropertyValue\"[\n\014EntityUpdate\022" +
      "\017\n\007classId\030\001 \002(\005\022\020\n\010entityId\030\002 \002(\003\022(\n\017pr" +
      "opertyUpdates\030\003 \003(\0132\017.PropertyUpdate\"H\n\016" +
      "PropertyUpdate\022\024\n\014propertyCode\030\001 \002(\005\022 \n\010",
      "newValue\030\002 \002(\0132\016.PropertyValue\"\035\n\rProper" +
      "tyValue\022\014\n\004data\030\001 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ObjectGraph_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ObjectGraph_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ObjectGraph_descriptor,
              new java.lang.String[] { "DomainId", "DataVersionScheme", "DataVersion", "EntityValues", "EntityUpdates", },
              GraphData.ObjectGraph.class,
              GraphData.ObjectGraph.Builder.class);
          internal_static_EntityValue_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_EntityValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EntityValue_descriptor,
              new java.lang.String[] { "ClassId", "EntityId", "PropertyValues", },
              GraphData.EntityValue.class,
              GraphData.EntityValue.Builder.class);
          internal_static_EntityUpdate_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_EntityUpdate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EntityUpdate_descriptor,
              new java.lang.String[] { "ClassId", "EntityId", "PropertyUpdates", },
              GraphData.EntityUpdate.class,
              GraphData.EntityUpdate.Builder.class);
          internal_static_PropertyUpdate_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_PropertyUpdate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PropertyUpdate_descriptor,
              new java.lang.String[] { "PropertyCode", "NewValue", },
              GraphData.PropertyUpdate.class,
              GraphData.PropertyUpdate.Builder.class);
          internal_static_PropertyValue_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_PropertyValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PropertyValue_descriptor,
              new java.lang.String[] { "Data", },
              GraphData.PropertyValue.class,
              GraphData.PropertyValue.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
